export const FETCH_POPULAR_MOVIES_REQUEST = 'FETCH_POPULAR_MOVIES_REQUEST';
export const FETCH_POPULAR_MOVIES_SUCCESS = 'FETCH_POPULAR_MOVIES_SUCCESS';
export const FETCH_POPULAR_MOVIES_FAILURE = 'FETCH_POPULAR_MOVIES_FAILURE';

export const LOAD_FETCH_POPULAR_MOVIES_REQUEST =
  'LOAD_FETCH_POPULAR_MOVIES_REQUEST';
export const LOAD_FETCH_POPULAR_MOVIES_SUCCESS =
  'LOAD_FETCH_POPULAR_MOVIES_SUCCESS';
export const LOAD_FETCH_POPULAR_MOVIES_FAILURE =
  'LOAD_FETCH_POPULAR_MOVIES_FAILURE';

export const FETCH_MOVIE_REQUEST = 'FETCH_MOVIE_REQUEST';
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS';
export const FETCH_MOVIE_FAILURE = 'FETCH_MOVIE_FAILURE';
